name: Meshkit Error Codes Utility Runner
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '**.go'

jobs:
  Update-error-codes:
    name: Error codes utility
    if: github.repository == 'khulnasoft/meshplay-operator'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        # token here with write access to meshplay-operator repo
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: 'master'

      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: 1.21

      - name: Run utility
        run: |
          go get github.com/khulnasoft/meshkit/cmd/errorutil
          go run github.com/khulnasoft/meshkit/cmd/errorutil -d . update --skip-dirs meshplay -i ./helpers -o ./helpers
      # to update errorutil* files in meshplay-operator repo
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@khulnasoft.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: 'run error codes utility'
          file_pattern: helpers/ **.go

      # to push changes to meshplay docs
      - name: Checkout meshplay
        uses: actions/checkout@master
        with:
          repository: 'khulnasoft/meshplay'
          # token with write access to meshplay repository
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: 'meshplay'
          ref: 'master'

      - name: Update and push docs
        run: |
          echo '{ "errors_export": "" }' | jq --slurpfile export ./helpers/errorutil_errors_export.json '.errors_export = $export[0]' > ./meshplay/docs/_data/errorref/meshplay-operator_errors_export.json
          cd ./meshplay
          git config user.name l5io
          git config user.email ci@khulnasoft.com
          if git diff --exit-code --quiet
          then
            echo "No changes to commit"
            exit
          fi
          git add ./docs/_data/errorref/meshplay-operator_errors_export.json
          git commit -m "[Docs] Error Code Reference: Updated codes for Meshplay Operator" --signoff
          git push origin master
